### ISSUE TITLE
Possibly out of league of the mod suggestion.

### ISSUE THREAD

**Issue by StoneLegion** [OLEGSHA/CustomNetherScale#1]
We been using 1.7.10 as well and found this mod and it's amazing. An issue we are having and this has nothing to do with the mod, but is some players are going through the portal and end up touching the portal blocks and looping back.

I'm wondering if it's not too hard to maybe add an option to move the player a couple blocks maybe a config option from the portal. So if I set to 3 with yes a chance they might fall into lava, etc. Might be better then having them back into the portal. Unless if it's not hard to say increase said platforms size?

**Comment by OLEGSHA** [comment]
~Whoa, what? Someone actually found a use for this mod? Amazing!~

I'm not sure I quite understand what happens. As far as I remember the player spawns inside portal blocks anyway. To teleport back the player should need to exit the portal frame and enter back in which I image wouldn't happen by chance. Could you elaborate a little on what exactly is going on?

**Comment by StoneLegion** [comment]
Hi there, Sorry I missed your reply. This a good example of my bad luck and it's not your Mod doing it rather we not sure what causes it. 

https://cdn.discordapp.com/attachments/682362773120090137/865123648082935808/2021-07-15_02-49-22.mp4


It happen before your mod was added.

**Comment by OLEGSHA** [comment]
I think I'll close this issue because it's off-topic and omg, how long was that?
